# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

extraScrapeConfigs: |
  - job_name: script-exporter-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ["script-exporter:9469"]
  - job_name: script-exporter-probe
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      script: ['ssh_probe']
    static_configs:
      - targets: ["script-exporter:9469"]