# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

extraScrapeConfigs: |
  - job_name: script-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["script-exporter:9469"]